# Generated by Django 3.1.7 on 2022-08-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
