# Generated by Django 3.1.7 on 2022-08-21 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_useraccount_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
